name: Publish component version updates in Confluence
on:
  release:
    types:
      - published

jobs:
  publish:
    name: Repository dispatch
    if: ${{ startsWith(github.ref_name, 'v') }}
    runs-on:
    - self-hosted
    - small
    steps:
      - run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MESOSPHERECI_USER_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/mesosphere/dkp-infra-tools/dispatches \
            -d '{"event_type":"confluence-docs","client_payload":{"docs_type":"kib","ref":"${{ github.ref_name }}"}}'
